export const REACT_QUERY_KEYS = {
  PROFILE_WITH_ID: "PROFILE_WITH_IDS",
  INFLUENCER_INFO_UPLOAD: "INFLUENCER_INFO_UPLOAD",
  PROFILE: "PROFILE",
  BUSINESS_SIGNUP: "BUSINESS_SIGNUP",
  ALL_CAMPAIGNS: "ALL_CAMPAIGNS",
  APPLY_CAMPAIGN: "APPLY_CAMPAIGN",
};
