export const SOCKET_CONSTANTS = {
  NEW_CAMPAIGN: "NEW_CAMPAIGN",
  USER_TYPIING_STARTED: "USER_TYPIING",
  USER_TYPING_ENDED: "USER_TYPING_ENDED",
  USER_CONNECTED_FORUM: "USER_CONNECTED_FORUM",
  USER_NEW_MESSAGE: "USER_NEW_MESSAGE",
  USER_NEW_MESSAGE_SENT: "USER_NEW_MESSAGE_SENT",
  MESSAGE_FAILED: "MESSAGE_FAILED",
  GENERAL_INFO_FORUM: "GENERAL_INFO_FORUM",
  COMPLETED_CAMPAIGN: "COMPLETED_CAMPAIGN",
};
